// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvF_6-eeNVcNP5l6O0T9rfAtzC6H7jQ08',
    appId: '1:748913004062:web:e8602abeec54757d5ae80f',
    messagingSenderId: '748913004062',
    projectId: 'fila-virtual-bcp',
    authDomain: 'fila-virtual-bcp.firebaseapp.com',
    storageBucket: 'fila-virtual-bcp.firebasestorage.app',
    measurementId: 'G-QYVR2KPM5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnU_-DXtSKPLGhtIYI62jRj8tInS56cdQ',
    appId: '1:748913004062:android:a2d24e50c24beb0a5ae80f',
    messagingSenderId: '748913004062',
    projectId: 'fila-virtual-bcp',
    storageBucket: 'fila-virtual-bcp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC23rj4DbflIMk54mhAfrRj0pVEF6kjquQ',
    appId: '1:748913004062:ios:8c5722b5dc1948275ae80f',
    messagingSenderId: '748913004062',
    projectId: 'fila-virtual-bcp',
    storageBucket: 'fila-virtual-bcp.firebasestorage.app',
    iosBundleId: 'com.example.filaVirtualBcp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC23rj4DbflIMk54mhAfrRj0pVEF6kjquQ',
    appId: '1:748913004062:ios:8c5722b5dc1948275ae80f',
    messagingSenderId: '748913004062',
    projectId: 'fila-virtual-bcp',
    storageBucket: 'fila-virtual-bcp.firebasestorage.app',
    iosBundleId: 'com.example.filaVirtualBcp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvF_6-eeNVcNP5l6O0T9rfAtzC6H7jQ08',
    appId: '1:748913004062:web:d9f5694d17affef65ae80f',
    messagingSenderId: '748913004062',
    projectId: 'fila-virtual-bcp',
    authDomain: 'fila-virtual-bcp.firebaseapp.com',
    storageBucket: 'fila-virtual-bcp.firebasestorage.app',
    measurementId: 'G-EKTGV23D3V',
  );
}
